name: CI

on:
  push:
    branches: [trunk]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flake-check:
    runs-on: atlas
    container: nixos/nix:latest
    env:
      NIX_CONFIG: |
        experimental-features = nix-command flakes
        substituters = https://attic.candee.baby/canix https://cache.nixos.org
        trusted-public-keys = canix:uqr0nD3I0mfj9BYfZgTZHMaDKfI2yCTtSA5JGTWKUeg= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Nix flake check
        run: nix flake check --keep-going --print-build-logs

  release-checks:
    runs-on: atlas
    container: rust:1.85-bookworm
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install Rust components
        run: rustup component add clippy rustfmt

      - name: Install cargo-binstall
        run: |
          base="https://raw.githubusercontent.com/cargo-bins"
          script="$base/cargo-binstall/main/install-from-binstall-release.sh"
          curl -L --proto '=https' --tlsv1.2 -sSf "$script" | bash

      - name: Install cargo tools
        run: |
          cargo binstall -y --locked \
            cargo-audit@0.22.1 \
            cargo-deny@0.18.3 \
            cargo-nextest@0.9.100

      - name: Rustfmt
        run: cargo fmt --all -- --check

      - name: Test all features
        run: cargo nextest run --all-features

      - name: Test no default features
        run: cargo nextest run --no-default-features

      - name: Clippy all features
        run: cargo clippy --all-targets --all-features -- --deny warnings

      - name: Clippy no default features
        run: cargo clippy --all-targets --no-default-features -- --deny warnings

      - name: Rustdoc
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --all-features

      - name: Package contents
        run: cargo package --list

      - name: Publish dry run
        run: cargo publish --dry-run

      - name: Dependency policy
        run: cargo deny check

      - name: Dependency audit
        run: cargo audit
